services:
  alpine: { build: { dockerfile: alpine.Dockerfile } }
  arch:   { build: { dockerfile: arch.Dockerfile   } }
  debian: { build: { dockerfile: debian.Dockerfile } }
  fedora: { build: { dockerfile: fedora.Dockerfile } }
  ubuntu: { build: { dockerfile: ubuntu.Dockerfile } }
